// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
namespace EmprestimosTests
{
    [TestFixture]
    public class EmprestimoNormalTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void emprestimoNormal()
        {
            driver.Navigate().GoToUrl("https://localhost:44306/EmprestimoModels/Create");
            driver.Manage().Window.Size = new System.Drawing.Size(834, 590);
            driver.FindElement(By.Id("LivroId")).Click();
            {
                var dropdown = driver.FindElement(By.Id("LivroId"));
                dropdown.FindElement(By.XPath("//option[. = 'Percy Jackson']")).Click();
            }
            driver.FindElement(By.Id("ClienteId")).Click();
            driver.FindElement(By.Id("Emprestado")).Click();
            driver.FindElement(By.Id("PrevisaoDevolucao")).Click();
            driver.FindElement(By.Id("verificarEmprestimo")).Click();
            driver.FindElement(By.LinkText("Criar")).Click();
            Assert.NotNull(driver.FindElement(By.XPath("//h1[contains(text(), 'Create')]")));
        }
    }
}

